### ISSUE TITLE
Extend support for Windows 11

### ISSUE THREAD

**Issue by HuyHung1408** [bceenaeiklmr/HideMyIcon#1]
What a nice program I use when I used Windows 10, but recently I upgraded to Windows 11. Although it still works so far, but I discovered a little bug as you can see in the video. Can you fix it?

https://user-images.githubusercontent.com/86362423/173097294-36b07175-faad-4ddf-a9c4-513a7d04f5d9.mp4

**Comment by krypdoh** [comment]
Have the same issue on Windows 11.  Unable to manipulate desktop icons -- can't move or double-click.

**Comment by bceenaeiklmr** [comment]
Hi @HuyHung1408, hi @krypdoh,

thank you for the video.

Unfortunately, I use Windows 10 at this very moment so I am not able to make a real test.

In my opinion, the problem relates to a changed class name of the desktop.

Let me think about it and do some research.

Cheers,
Bence

**Comment by bceenaeiklmr** [comment]
Hi @HuyHung1408, hi @krypdoh,

I just updated the script today, and the logic is simplified therefore the whole script is more stable.

Unfortunately, I really overcomplicated the 'things' in the previous version.

As always, let me know your thoughts!

Thank you!

cheers,
Bence

**Comment by HuyHung1408** [comment]
hi @bceenaeiklmr, sorry for the late reply because I've been so busy these days. Glad that you made it simpler than before, unfortunately, as I tried it in Windows 11ver 22H2, it does not hide the icon as I expected.

**Comment by StudioNirin** [comment]
Any hope / news on this working on current windows 11?

**Comment by krypdoh** [comment]
Any chance on a Windows 11 update? It worked great on 10. Thanks!!

**Comment by krypdoh** [comment]
The v2 script seems to be working great on Windows11. NICE WORK!

**Comment by bceenaeiklmr** [comment]
He @krypdoh, thank you for your feedback! I will note that in the readme file. @HuyHung1408 JFYI.

I will close this issue, @krypdoh reported v2 version works on Windows 11.

cheers, Bence

**Comment by HuyHung1408** [comment]
Thanks! I will check that again.
